install:
  - npm install
  - node_modules/.bin/webpack
language: node_js
node_js:
    - "7.2.0"
services:
  - mongodb
after_success:
  - npm run coveralls
notifications:
  slack: thecodework:JOr2xDNgdivXC6eKt2R5Rvwt